import { Navigation } from '../componentes/Navigation';
import { Example } from '../componentes/Example';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>Ipuc Llanaditas</title>
      </head>
      <body>
<Navigation />
        {children}
      </body>
    </html>
  );
}
